// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilmcincnzadrjhaxnmcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsbWNpbmNuemFkcmpoYXhubWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODk0MjUsImV4cCI6MjA3Mzc2NTQyNX0.ShjYaEqrdPN-FQ5qob52PFq70BduBBdg-zRY1O7-DoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});